# Generated by Django 4.1.6 on 2023-02-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
